// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeA5Ea9nsTA5bFlP8Oc8MvDm7uXRFJ_OQ',
    appId: '1:654852995693:web:3c90df57315b3e23fd1d64',
    messagingSenderId: '654852995693',
    projectId: 'pg-mart-84d31',
    authDomain: 'pg-mart-84d31.firebaseapp.com',
    storageBucket: 'pg-mart-84d31.firebasestorage.app',
    measurementId: 'G-BS9RNB0RWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjO70oqUZygLalK3XN9BnN-rZ8JKaXwkQ',
    appId: '1:654852995693:android:c236c6357c353a78fd1d64',
    messagingSenderId: '654852995693',
    projectId: 'pg-mart-84d31',
    storageBucket: 'pg-mart-84d31.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3qA4UoVmc9TLjY5BxnnnQDiE0lU60n_8',
    appId: '1:654852995693:ios:fb55c0e06ce88ecefd1d64',
    messagingSenderId: '654852995693',
    projectId: 'pg-mart-84d31',
    storageBucket: 'pg-mart-84d31.firebasestorage.app',
    iosBundleId: 'com.pgmart.pgmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3qA4UoVmc9TLjY5BxnnnQDiE0lU60n_8',
    appId: '1:654852995693:ios:f945077384888c9cfd1d64',
    messagingSenderId: '654852995693',
    projectId: 'pg-mart-84d31',
    storageBucket: 'pg-mart-84d31.firebasestorage.app',
    iosBundleId: 'com.pgmart.pgmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBeA5Ea9nsTA5bFlP8Oc8MvDm7uXRFJ_OQ',
    appId: '1:654852995693:web:8d93170d983cb9ccfd1d64',
    messagingSenderId: '654852995693',
    projectId: 'pg-mart-84d31',
    authDomain: 'pg-mart-84d31.firebaseapp.com',
    storageBucket: 'pg-mart-84d31.firebasestorage.app',
    measurementId: 'G-TV14RK20XZ',
  );
}